export default {
    helloWorld:'اهلا بالعالم',
    clickHere:'اضغط هنا',
    electroics:'الالكترونيات',
    beauty:'التجميل',
    furniture:'المطبخ والمنزل',
    shoes:'الازياء',
    newArrivel:'وصل حديثا',
    more:'المزيد',
    product:'اسم المنتج',
    category:'كاتيجوري',
    sr100:'١٠٠ رس',
   sectionName:'اسم السكشن',
   mostImportantStore:'اهم المتاجر المميزه',
   storeName:'اسم المتجر',
   rate:'التصنيف',
   adArea:'مساحه اعلانيه',
    news:'كل جديد',
    here:'هنا',
    homepage:'تصفح',
    sections:'الاقسام',
    favourite:'المفضله',
    busket:'سله المشتريات',
    search:'بحث',
    whoarewe:'من نحن',
    contactus:'تواصل معنا',
    logout:'تسجيل الخروج'
} 