export default {
    helloWorld:'hello world',
    clickHere:'click here',
    electroics:'electronics',
    beauty:'beauty',
    furniture:'furniture',
    shoes:'shoes',
    newArrivel:'new arrivel',
    more:'more',
    product:'product',
    category:'category',
    sr100:'100 sr',
    sectionName:'section name',
    mostImportantStore:'the most important stores',
    storeName:'store name',
    rate:'rate',
    adArea:'Ad area',
    news:'news',
    here:'here',
}